/**
 * 问天刷题舱 · 题库数据
 * 感恩中国近现代科学家奖助学金 笔试题库
 *
 * 题型 type:
 *   single   单选（answer 为正确选项下标，从 0 开始）
 *   multiple 多选（answer 为正确选项下标数组）
 *   fill     填空（answer 为参考答案字符串，keywords 为判分关键词组，全部命中即判对）
 *   flash    简答/记忆闪卡（answer 为参考答案，自评掌握）
 *
 * 分区 section:
 *   scientist 普适题（科学家事迹 / 两弹一星 / 航天成就，各校通用）—— 主仓库只放这一区
 *   school    校情题（本校校史校情）。主仓库刻意不含任何校情题：
 *             把仓库里的 school.example.js 复制成 my-school.js，改成自己学校的题目，
 *             刷新页面后会自动合并进题库，无需改动本文件。
 *
 * 来源 source 标注：第六届真题 / 2022回忆卷 / 2023回忆卷 / 博雅书院真题 / 知识点整理
 */
window.QUESTION_BANK = [
  { id: "s01", type: "single", section: "scientist", source: "第六届真题",
    question: "1964年10月16日，我国第一颗（ ）在新疆罗布泊爆炸成功。",
    options: ["核弹", "原子弹", "导弹", "氢弹"], answer: 1,
    note: "1964年10月16日，第一颗原子弹爆炸成功。" },
  { id: "s02", type: "single", section: "scientist", source: "第六届真题",
    question: "在“两弹一星”功勋奖章获得者中，被誉为“中国原子弹之父”的是（ ）。其妻子何泽慧是杰出的物理学家，夫妻二人被称为中国的“居里夫妇”。",
    options: ["郭永怀", "钱三强", "黄纬禄", "任新民"], answer: 1,
    note: "钱三强：中国原子弹之父、中国原子能科学之父。" },
  { id: "s03", type: "single", section: "scientist", source: "第六届真题",
    question: "关于科学与科学家的关系，正确的说法是（ ）。",
    options: ["科学没有国界，但科学家是有祖国的", "科学有国界，科学家也有国界", "科学没有国界，科学家也没有国界", "科学、科学家跟国界没有任何关系"],
    answer: 0, note: "钱三强名言：科学没有国界，但科学家有祖国。" },
  { id: "s04", type: "single", section: "scientist", source: "第六届真题",
    question: "詹天佑说过：“各出所学，各尽所知，使国家富强不受外侮，足以自立于地球之上。”这句话强调在自觉维护国家利益时（ ）。",
    options: ["既要体现中国人维护国家利益的坚定信念，又要体现出中国公民的文明形象和风范", "树立民族自尊心和自豪感", "要献身于国家科技事业", "要承担起对国家应尽的义务"],
    answer: 0 },
  { id: "s05", type: "single", section: "scientist", source: "第六届真题",
    question: "袁隆平院士利用野生水稻和普通水稻多次杂交，培育出高产杂交水稻新品种，这是利用了生物多样性的哪一层次？（ ）",
    options: ["遗传多样性", "农作物多样性", "物种多样性", "生态系统多样性"], answer: 0 },
  { id: "s06", type: "single", section: "scientist", source: "第六届真题",
    question: "中国天眼工程 FAST 是世界上最大的（ ），其总设计师兼首席科学家是（ ）。",
    options: ["巨型计算机；南仁东", "量子科学实验卫星；潘建伟", "射电望远镜；潘建伟", "射电望远镜；南仁东"],
    answer: 3, note: "500米口径球面射电望远镜，南仁东主持选址建设22年。" },
  { id: "s07", type: "single", section: "scientist", source: "第六届真题",
    question: "由理论物理转向氢弹研究，解决了热核物理一系列关键性问题、使氢弹原理取得突破，被誉为“中国氢弹之父”的是（ ）。",
    options: ["茅以升", "钱三强", "王淦昌", "于敏"], answer: 3,
    note: "于敏：中国氢弹之父、中国中子弹之父。" },
  { id: "s08", type: "single", section: "scientist", source: "第六届真题",
    question: "我国第一代核潜艇总设计师，为国家利益隐姓埋名三十年，为核潜艇研制和跨越式发展作出巨大贡献的是（ ）。",
    options: ["黄旭华", "钱伟长", "周培源", "童第周"], answer: 0 },
  { id: "s09", type: "single", section: "scientist", source: "第六届真题",
    question: "我国研究与发展杂交水稻的开创者，被誉为“世界杂交水稻之父”的科学家是（ ）。",
    options: ["李四光", "袁隆平", "侯德榜", "周培源"], answer: 1 },
  { id: "s10", type: "single", section: "scientist", source: "第六届真题",
    question: "被誉为“中国航天之父”“中国导弹之父”“中国自动化控制之父”和“火箭之王”的是（ ）。",
    options: ["钱三强", "钱伟长", "钱学森", "侯德榜"], answer: 2 },
  { id: "s11", type: "single", section: "scientist", source: "第六届真题",
    question: "童第周被誉为（ ）。",
    options: ["中国克隆之父", "当代神农", "中国核武器之父", "火箭之王"], answer: 0 },
  { id: "s12", type: "single", section: "scientist", source: "第六届真题",
    question: "茅以升主持设计的（ ），是我国第一座由中国人自己设计建造的铁路公路两用桥。",
    options: ["虎门大桥", "武汉长江大桥", "南京长江大桥", "钱塘江大桥"], answer: 3 },
  { id: "s13", type: "single", section: "scientist", source: "第六届真题",
    question: "我国第一颗氢弹爆炸成功的时间是（ ）。",
    options: ["1966年6月16日", "1966年6月17日", "1967年6月16日", "1967年6月17日"], answer: 3,
    note: "1967年6月17日，第一颗氢弹空爆试验成功。" },
  { id: "s14", type: "single", section: "scientist", source: "第六届真题",
    question: "我国第一颗人造地球卫星成功发射的时间为（ ）。",
    options: ["1969年4月24日", "1969年4月25日", "1970年4月24日", "1970年4月25日"], answer: 2,
    note: "1970年4月24日，东方红一号发射成功；4月24日后被设为“中国航天日”。" },
  { id: "s15", type: "single", section: "scientist", source: "第六届真题",
    question: "我国完全自主研制的世界上第一颗空间量子科学实验卫星是（ ）。",
    options: ["墨子号", "祝融号", "嫦娥号", "北斗号"], answer: 0 },
  { id: "s16", type: "single", section: "scientist", source: "第六届真题",
    question: "中国航天日的具体日期是每年的（ ）。",
    options: ["4月23日", "4月24日", "4月25日", "4月26日"], answer: 1 },
  { id: "s17", type: "single", section: "scientist", source: "第六届真题",
    question: "首次在月球取土并返回的是（ ）。",
    options: ["嫦娥四号", "长征三号", "嫦娥五号", "天宫一号"], answer: 2 },
  { id: "s18", type: "single", section: "scientist", source: "第六届真题",
    question: "在（ ）年，中国实现火星探测（天问一号发射）。",
    options: ["2018", "2019", "2020", "2022"], answer: 2 },
  { id: "s19", type: "single", section: "scientist", source: "博雅书院真题",
    question: "被称为“中国的莱特”（中国始创飞行大家）的是（ ）。",
    options: ["钱学森", "冯如", "梁守槃", "屠守锷"], answer: 1 },
  { id: "s20", type: "single", section: "scientist", source: "博雅书院真题",
    question: "我国首颗探月卫星是（ ）。",
    options: ["玉兔一号", "嫦娥一号", "天问一号", "天宫一号"], answer: 1 },
  { id: "s21", type: "single", section: "scientist", source: "博雅书院真题",
    question: "我国人造卫星技术和深空探测技术的开创者之一，被称为中国航天的“大总师”，“东方红一号”“北斗导航试验卫星”工程总设计师是（ ）。",
    options: ["吴自良", "钱骥", "孙家栋", "钱三强"], answer: 2 },
  { id: "s22", type: "single", section: "scientist", source: "博雅书院真题",
    question: "（ ）领导研究建立了运动员禁用的五大类100种药物的分析及确证方法，创建兴奋剂检测中心，使我国成为亚运会历史上第一个由承办国独立进行兴奋剂检测的国家。",
    options: ["周同惠", "钱学森", "于敏", "钟南山"], answer: 0 },
  { id: "s23", type: "single", section: "scientist", source: "博雅书院真题",
    question: "我国著名核物理学家，核武器研制工作的开拓者和奠基者，为我国核武器、原子武器研发做出重要贡献，被称为“两弹元勋”的是（ ）。",
    options: ["顾方舟", "倪光南", "叶培建", "邓稼先"], answer: 3 },
  { id: "s24", type: "single", section: "scientist", source: "博雅书院真题",
    question: "被誉为“中国工程科学界支柱性的科学家”“中国科技众帅之帅”的科学家是（ ）。",
    options: ["朱光亚", "南仁东", "吴自良", "王淦昌"], answer: 0 },

  { id: "s25", type: "single", section: "scientist", source: "公开资料整理",
    question: "我国首位获得诺贝尔科学奖项的女科学家、青蒿素的发现者是（ ）。",
    options: ["屠呦呦", "何泽慧", "林巧稚", "谢希德"], answer: 0,
    note: "2015年诺贝尔生理学或医学奖（与坎贝尔、大村智共同获得）；2019年获“共和国勋章”。" },
  { id: "s26", type: "single", section: "scientist", source: "公开资料整理",
    question: "被誉为“中国稀土之父”、2008年度国家最高科学技术奖获得者的是（ ）。",
    options: ["徐光宪", "侯德榜", "闵恩泽", "张存浩"], answer: 0 },
  { id: "s27", type: "single", section: "scientist", source: "公开资料整理",
    question: "被誉为“中国预警机之父”、2012年度国家最高科学技术奖获得者的是（ ）。",
    options: ["王小谟", "刘永坦", "贲德", "陈芳允"], answer: 0 },
  { id: "s28", type: "single", section: "scientist", source: "公开资料整理",
    question: "被誉为“黄土之父”、中国地球环境科学奠基人之一的是（ ）。",
    options: ["刘东生", "李四光", "竺可桢", "丁林"], answer: 0 },
  { id: "s29", type: "single", section: "scientist", source: "公开资料整理",
    question: "被誉为“中国肝胆外科之父”、2005年度国家最高科学技术奖获得者的是（ ）。",
    options: ["吴孟超", "王振义", "钟南山", "侯云德"], answer: 0 },
  { id: "s30", type: "single", section: "scientist", source: "公开资料整理",
    question: "我国载人航天工程首任总设计师、2003年度国家最高科学技术奖获得者、2024年被授予“共和国勋章”的是（ ）。",
    options: ["王永志", "戚发轫", "王希季", "屠守锷"], answer: 0 },
  { id: "s31", type: "single", section: "scientist", source: "立德树人网",
    question: "2009年放弃英国优厚待遇回国任教吉林大学，主持研制“地壳一号”万米钻机的地球物理学家是（ ）。",
    options: ["黄大年", "南仁东", "黄旭华", "程开甲"], answer: 0,
    note: "2017年1月8日病逝，年仅58岁；习近平总书记评价其“心有大我、至诚报国”；2024年被追授“人民教育家”国家荣誉称号。" },
  { id: "s32", type: "single", section: "scientist", source: "公开资料整理",
    question: "我国首艘货运飞船，被称为太空“快递小哥”的是（ ）。",
    options: ["天舟一号", "天和核心舱", "问天实验舱", "梦天实验舱"], answer: 0 },
  { id: "s33", type: "single", section: "scientist", source: "公开资料整理",
    question: "中国载人航天工程“三步走”的第一步任务，由哪次任务完成？（ ）",
    options: ["神舟一号", "神舟五号", "神舟七号", "天宫一号"], answer: 1,
    note: "第一步：发射载人飞船，将航天员安全送入近地轨道并返回——2003年神舟五号（杨利伟）标志第一步完成。" },

  { id: "m01", type: "multiple", section: "scientist", source: "第六届真题",
    question: "执行神舟十四号飞行任务的航天员是（ ）。",
    options: ["陈冬", "刘洋", "翟志刚", "蔡旭哲"], answer: [0, 1, 3],
    note: "神舟十四号乘组：陈冬、刘洋、蔡旭哲。" },
  { id: "m02", type: "multiple", section: "scientist", source: "第六届真题",
    question: "2013年2月，习近平在视察酒泉卫星发射中心时，勉励大家发扬“____”精神、“____”精神和“____”精神，以民族复兴为己任，扎根大漠，报效祖国和人民。",
    options: ["两弹一星", "载人航天", "东风", "航空母舰"], answer: [0, 1, 2] },
  { id: "m03", type: "multiple", section: "scientist", source: "第六届真题",
    question: "2020年9月11日，习近平在科学家座谈会上指出，希望广大科技工作者不忘初心、牢记使命，秉持____和____至上，继承和发扬老一辈科学家____的优秀品质，弘扬“____”精神，主动肩负起历史重任。",
    options: ["国家利益", "人民利益", "胸怀祖国、服务人民", "两弹一星"], answer: [0, 1, 2, 3] },
  { id: "m04", type: "multiple", section: "scientist", source: "第六届真题",
    question: "“两弹一星”是指（ ）。",
    options: ["核弹", "航空母舰", "导弹", "人造卫星"], answer: [0, 2, 3] },
  { id: "m05", type: "multiple", section: "scientist", source: "第六届真题",
    question: "“两弹一星”精神的内容主要包括（ ）。",
    options: ["热爱祖国、无私奉献", "自力更生、艰苦奋斗", "大力协同、勇于登攀", "实事求是、积极团结"],
    answer: [0, 1, 2],
    note: "两弹一星精神24字：热爱祖国、无私奉献，自力更生、艰苦奋斗，大力协同、勇于登攀。" },
  { id: "m06", type: "multiple", section: "scientist", source: "公开资料整理",
    question: "2019年获得“共和国勋章”的科学家包括（ ）。（注意：整套名单中还有黄旭华、屠呦呦）",
    options: ["于敏", "孙家栋", "袁隆平", "李四光"], answer: [0, 1, 2],
    note: "2019年9月17日授予于敏、申纪兰、孙家栋、李延年、张富清、袁隆平、黄旭华、屠呦呦“共和国勋章”，其中5位是科学家。" },
  { id: "m07", type: "multiple", section: "scientist", source: "公开资料整理",
    question: "载人航天精神的内容包括（ ）。",
    options: ["特别能吃苦", "特别能战斗", "特别能攻关", "特别能奉献"], answer: [0, 1, 2, 3] },
  { id: "m08", type: "multiple", section: "scientist", source: "公开资料整理",
    question: "1986年3月联名向中央提出跟踪外国战略性高技术发展建议、催生“863”计划的科学家是（ ）。",
    options: ["王大珩", "王淦昌", "杨嘉墀", "陈芳允"], answer: [0, 1, 2, 3] },
  { id: "m09", type: "multiple", section: "scientist", source: "公开资料整理",
    question: "下列获得“人民科学家”国家荣誉称号的科学家有（ ）。",
    options: ["叶培建", "吴文俊", "南仁东", "袁隆平"], answer: [0, 1, 2],
    note: "2019年授予叶培建、吴文俊、南仁东、顾方舟、程开甲“人民科学家”称号；2024年新增王小谟、赵忠贤。袁隆平获得的是“共和国勋章”。" },
  { id: "m10", type: "multiple", section: "scientist", source: "公开资料整理",
    question: "中国空间站的三个基本舱段是（ ）。",
    options: ["天和核心舱", "问天实验舱", "梦天实验舱", "天舟一号"], answer: [0, 1, 2],
    note: "天和核心舱 + 问天实验舱 + 梦天实验舱构成“T”字基本构型；天舟系列是货运飞船。" },

  { id: "f01", type: "fill", section: "scientist", source: "2022回忆卷",
    question: "钱学森创立的系统科学代表著作是《____》。",
    answer: "工程控制论", keywords: ["工程控制论"] },
  { id: "f02", type: "fill", section: "scientist", source: "2022回忆卷",
    question: "“中华星”（首颗由中国人发现的小行星）的发现者是____。",
    answer: "张钰哲", keywords: ["张钰哲"] },
  { id: "f03", type: "fill", section: "scientist", source: "2022回忆卷",
    question: "中国核武器的开拓者和奠基人是____。",
    answer: "邓稼先", keywords: ["邓稼先"] },
  { id: "f04", type: "fill", section: "scientist", source: "2022回忆卷",
    question: "我国首颗原子弹爆炸成功后，写下《清平乐·我国第一颗原子弹爆炸成功》的将军是____。",
    answer: "张爱萍", keywords: ["张爱萍"] },
  { id: "f05", type: "fill", section: "scientist", source: "2022回忆卷",
    question: "茅以升主持修建的钱塘江大桥于____年建成通车。",
    answer: "1937年（1937年9月26日铁路桥通车）", keywords: ["1937"] },
  { id: "f06", type: "fill", section: "scientist", source: "2022回忆卷",
    question: "我国第一座自行设计建造的公路铁路两用长江大桥是____。",
    answer: "武汉长江大桥", keywords: ["武汉长江大桥"] },
  { id: "f07", type: "fill", section: "scientist", source: "2022回忆卷",
    question: "我国首个火星探测器是____，搭载的火星车名为____。",
    answer: "天问一号；祝融号", keywords: ["天问一号", "祝融号"] },
  { id: "f08", type: "fill", section: "scientist", source: "2022回忆卷",
    question: "____是我国气象地理学家，我国现代气象事业的奠基人。",
    answer: "竺可桢", keywords: ["竺可桢"] },
  { id: "f09", type: "fill", section: "scientist", source: "2022回忆卷",
    question: "陈能宽用“____法”解决了原子弹重要部件的关键难题。",
    answer: "内爆法", keywords: ["内爆"] },
  { id: "f10", type: "fill", section: "scientist", source: "2022回忆卷",
    question: "陈能宽毕业于____（校名）。",
    answer: "国立交通大学", keywords: ["交通大学"] },
  { id: "f11", type: "fill", section: "scientist", source: "2022回忆卷",
    question: "北斗导航卫星的发射地是____卫星发射中心。",
    answer: "西昌", keywords: ["西昌"] },
  { id: "f12", type: "fill", section: "scientist", source: "2022回忆卷",
    question: "周培源的主要研究方向是____。",
    answer: "流体力学湍流理论", keywords: ["湍流"] },
  { id: "f13", type: "fill", section: "scientist", source: "2022回忆卷",
    question: "被誉为“中国克隆之父”的是____。",
    answer: "童第周", keywords: ["童第周"] },
  { id: "f14", type: "fill", section: "scientist", source: "2022回忆卷",
    question: "被誉为“当代毕昇”、发明汉字激光照排系统的是____。",
    answer: "王选", keywords: ["王选"] },
  { id: "f15", type: "fill", section: "scientist", source: "2022回忆卷",
    question: "地动仪的发明者是____。",
    answer: "张衡", keywords: ["张衡"] },
  { id: "f16", type: "fill", section: "scientist", source: "2022回忆卷",
    question: "“两弹一星”元勋中唯一一位以烈士身份被追授功勋奖章的是____。",
    answer: "郭永怀", keywords: ["郭永怀"] },
  { id: "f17", type: "fill", section: "scientist", source: "2022回忆卷",
    question: "郭永怀的妻子李佩被誉为“中国____之母”。",
    answer: "应用语言学", keywords: ["应用语言学"] },
  { id: "f18", type: "fill", section: "scientist", source: "2022回忆卷",
    question: "茅以升在炸毁钱塘江大桥时写下了八个字：____，____。",
    answer: "抗战必胜，此桥必复", keywords: ["抗战必胜", "此桥必复"] },
  { id: "f19", type: "fill", section: "scientist", source: "2022回忆卷",
    question: "提出“有序人类活动”概念的科学家是____。",
    answer: "叶笃正", keywords: ["叶笃正"] },
  { id: "f20", type: "fill", section: "scientist", source: "2022回忆卷",
    question: "首届国家最高科学技术奖（2000年度）的获奖人是____和____。",
    answer: "吴文俊、袁隆平", keywords: ["吴文俊", "袁隆平"] },
  { id: "f21", type: "fill", section: "scientist", source: "2022回忆卷",
    question: "中国微分几何学派的创始人是____。",
    answer: "苏步青", keywords: ["苏步青"] },
  { id: "f22", type: "fill", section: "scientist", source: "2023回忆卷",
    question: "黄纬禄在____（地点）进行水下导弹（潜地导弹）发射试验。",
    answer: "南京长江大桥", keywords: ["南京长江大桥"] },
  { id: "f23", type: "fill", section: "scientist", source: "2023回忆卷",
    question: "中国第一位女航天员是____。",
    answer: "刘洋", keywords: ["刘洋"] },
  { id: "f24", type: "fill", section: "scientist", source: "2023回忆卷",
    question: "詹天佑在____会议上捍卫了中国铁路主权。",
    answer: "远东铁路国际会议", keywords: ["远东铁路"] },
  { id: "f25", type: "fill", section: "scientist", source: "2023回忆卷",
    question: "姚桐斌回国后在____（单位）工作，他是唯一一位在国外入党的“两弹一星”元勋。",
    answer: "国防部第五研究院一分院", keywords: ["第五研究院"] },
  { id: "f26", type: "fill", section: "scientist", source: "2023回忆卷",
    question: "华罗庚的第一部著作是《____》。",
    answer: "堆垒素数论", keywords: ["堆垒素数论"] },
  { id: "f27", type: "fill", section: "scientist", source: "2023回忆卷",
    question: "钱学森创新性地首创了“____”理论及未来城市构想。",
    answer: "山水城市", keywords: ["山水城市"] },
  { id: "f28", type: "fill", section: "scientist", source: "2023回忆卷",
    question: "袁隆平发明出“____法”籼型杂交水稻，创建了著名的超级杂交稻技术体系。",
    answer: "三系法（后有“两系法”杂交水稻）", keywords: ["三系"] },
  { id: "f29", type: "fill", section: "scientist", source: "2023回忆卷",
    question: "被誉为“中国芯片之母”的科学家是____。",
    answer: "黄令仪", keywords: ["黄令仪"] },
  { id: "f30", type: "fill", section: "scientist", source: "2023回忆卷",
    question: "哥德巴赫猜想研究第一人（“1+2”证明者）是____。",
    answer: "陈景润", keywords: ["陈景润"] },
  { id: "f31", type: "fill", section: "scientist", source: "2023回忆卷",
    question: "被誉为“无线电泰斗”的是____。",
    answer: "李白", keywords: ["李白"] },
  { id: "f32", type: "fill", section: "scientist", source: "第六届真题",
    question: "2020年7月31日，____三号全球卫星导航系统全面建成并开通服务，我国成为世界上第____个独立拥有全球卫星导航系统的国家。",
    answer: "北斗；三", keywords: ["北斗", "三"] },
  { id: "f33", type: "fill", section: "scientist", source: "第六届真题",
    question: "中国首位获得诺贝尔科学奖项的女科学家是____。",
    answer: "屠呦呦", keywords: ["屠呦呦"] },
  { id: "f34", type: "fill", section: "scientist", source: "第六届真题",
    question: "第一位进入太空的华人宇航员是____。",
    answer: "王赣骏", keywords: ["王赣骏"] },
  { id: "f35", type: "fill", section: "scientist", source: "第六届真题",
    question: "地质学家____运用力学观点研究地壳运动，创立了____（学说）。",
    answer: "李四光；地质力学", keywords: ["李四光", "地质力学"] },
  { id: "f36", type: "fill", section: "scientist", source: "第六届真题",
    question: "我国杰出的铁路工程师____在1905年开工的____铁路建设中巧妙采用“____”字形线路解决爬坡困难。",
    answer: "詹天佑；京张铁路；人", keywords: ["詹天佑", "京张", "人"] },
  { id: "f37", type: "fill", section: "scientist", source: "第六届真题",
    question: "我国科学家钮经义等人在世界上第一个用人工方法合成结晶____。",
    answer: "牛胰岛素", keywords: ["牛胰岛素"] },
  { id: "f38", type: "fill", section: "scientist", source: "第六届真题",
    question: "我国航天事业的“航天四老”是指____、____、____、____。",
    answer: "任新民、黄纬禄、屠守锷、梁守槃", keywords: ["任新民", "黄纬禄", "屠守锷", "梁守槃"] },
  { id: "f39", type: "fill", section: "scientist", source: "第六届真题",
    question: "“人民科学家”国家荣誉称号获得者（2019年）包括：吴文俊、____、____、____、程开甲。",
    answer: "叶培建、顾方舟、南仁东", keywords: ["叶培建", "顾方舟", "南仁东"] },
  { id: "f40", type: "fill", section: "scientist", source: "知识点整理",
    question: "“糖丸爷爷”____发明了脊髓灰质炎疫苗，使我国消灭脊髓灰质炎。",
    answer: "顾方舟", keywords: ["顾方舟"] },
  { id: "f41", type: "fill", section: "scientist", source: "知识点整理",
    question: "“天眼之父”____在贵州选址建造 FAST，从预研到建成历时____年。",
    answer: "南仁东；22", keywords: ["南仁东", "22"] },
  { id: "f42", type: "fill", section: "scientist", source: "知识点整理",
    question: "神舟十七号（2023年10月26日发射）乘组航天员是____、____、____。",
    answer: "汤洪波、唐胜杰、江新林", keywords: ["汤洪波", "唐胜杰", "江新林"] },
  { id: "f43", type: "fill", section: "scientist", source: "知识点整理",
    question: "“一箭三星”最近一次发射（2022年9月27日）使用的是____运载火箭，发射地点是____卫星发射中心。",
    answer: "长征六号；太原", keywords: ["长征六号", "太原"] },
  { id: "f44", type: "fill", section: "scientist", source: "知识点整理",
    question: "中国探月工程总设计师（同时是中国第一颗人造地球卫星总设计师）是____。",
    answer: "孙家栋", keywords: ["孙家栋"] },
  { id: "f45", type: "fill", section: "scientist", source: "知识点整理",
    question: "钱三强在法国留学期间，在____（研究项目）上取得突破性成果。",
    answer: "铀核三裂变", keywords: ["三裂变"] },
  { id: "f46", type: "fill", section: "scientist", source: "知识点整理",
    question: "吴自良院士牵头攻克了原子弹的核心部件“____”（甲种分离膜）。",
    answer: "甲种分离膜", keywords: ["分离膜"] },
  { id: "f47", type: "fill", section: "scientist", source: "知识点整理",
    question: "被誉为“中国光学之父”的是____；他与王淦昌、陈芳允、杨嘉墀联名建议催生了“____计划”。",
    answer: "王大珩；863", keywords: ["王大珩", "863"] },
  { id: "f48", type: "fill", section: "scientist", source: "知识点整理",
    question: "黄纬禄被誉为“____之父”“东风-21之父”，他提出“一弹两用”设想，开拓了中国固体火箭与导弹发展道路。",
    answer: "巨浪", keywords: ["巨浪"] },
  { id: "f49", type: "fill", section: "scientist", source: "知识点整理",
    question: "王淦昌提出了用____实现核聚变的设想，使我国在该领域走在世界前列。",
    answer: "激光打靶（激光惯性约束核聚变）", keywords: ["激光"] },
  { id: "f50", type: "fill", section: "scientist", source: "知识点整理",
    question: "郭永怀发现上临界马赫数，发展了奇异摄动理论中的变形坐标法，即国际公认的____方法。",
    answer: "PLK方法", keywords: ["PLK"] },

  { id: "f51", type: "fill", section: "scientist", source: "公开资料整理",
    question: "中国载人航天工程于____年____月____日正式立项，代号“____工程”。",
    answer: "1992年9月21日；921", keywords: ["1992", "921"] },
  { id: "f52", type: "fill", section: "scientist", source: "公开资料整理",
    question: "我国首次载人飞行的时间是____，首飞航天员是____。",
    answer: "2003年10月15日；杨利伟", keywords: ["2003", "杨利伟"] },
  { id: "f53", type: "fill", section: "scientist", source: "公开资料整理",
    question: "神舟五号任务的成功使我国成为世界上第____个独立掌握载人航天技术的国家。",
    answer: "三", keywords: ["三"] },
  { id: "f54", type: "fill", section: "scientist", source: "公开资料整理",
    question: "中国人首次太空出舱活动由____完成，时间是____。",
    answer: "翟志刚；2008年9月27日", keywords: ["翟志刚", "2008"] },
  { id: "f55", type: "fill", section: "scientist", source: "公开资料整理",
    question: "我国首次空间交会对接：____年11月3日，____飞船与____目标飞行器对接成功。",
    answer: "2011；神舟八号；天宫一号", keywords: ["2011", "天宫一号"] },
  { id: "f56", type: "fill", section: "scientist", source: "公开资料整理",
    question: "我国首次太空授课于____年6月20日由神舟十号乘组完成，主讲老师是____。",
    answer: "2013；王亚平", keywords: ["2013", "王亚平"] },
  { id: "f57", type: "fill", section: "scientist", source: "公开资料整理",
    question: "我国首艘货运飞船是____，于____年4月20日发射成功。",
    answer: "天舟一号；2017", keywords: ["天舟一号", "2017"] },
  { id: "f58", type: "fill", section: "scientist", source: "公开资料整理",
    question: "中国空间站首个舱段（在轨组装建造开端）是____，发射时间是____。",
    answer: "天和核心舱；2021年4月29日", keywords: ["天和核心舱", "2021"] },
  { id: "f59", type: "fill", section: "scientist", source: "公开资料整理",
    question: "中国空间站“T”字基本构型于____年11月3日在轨组装完成；习近平在新年贺词中宣布空间站全面建成的时间是____。",
    answer: "2022；2022年12月31日", keywords: ["2022"] },
  { id: "f60", type: "fill", section: "scientist", source: "公开资料整理",
    question: "我国载人月球探测工程的目标是____年前实现中国人首次登陆月球。",
    answer: "2030", keywords: ["2030"] },
  { id: "f61", type: "fill", section: "scientist", source: "公开资料整理",
    question: "我国探月工程于____年正式启动，____年嫦娥一号实现首次绕月飞行。",
    answer: "2004；2007", keywords: ["2004", "2007"] },
  { id: "f62", type: "fill", section: "scientist", source: "科技部官网",
    question: "国家最高科学技术奖于____年设立、____年首次颁奖。",
    answer: "1999；2000", keywords: ["1999", "2000"] },
  { id: "f63", type: "fill", section: "scientist", source: "科技部官网",
    question: "国家最高科学技术奖空缺的年度是：2004、2015、____、____年度。",
    answer: "2021；2022", keywords: ["2021", "2022"] },
  { id: "f64", type: "fill", section: "scientist", source: "科技部官网",
    question: "2016年度国家最高科学技术奖获得者是____和____（后者是该奖唯一女性获奖者，也是唯一的诺贝尔奖得主）。",
    answer: "赵忠贤；屠呦呦", keywords: ["赵忠贤", "屠呦呦"] },
  { id: "f65", type: "fill", section: "scientist", source: "科技部官网",
    question: "2023年度国家最高科学技术奖获得者是____和____（后者是该奖历史上最年轻的获奖者）。",
    answer: "李德仁；薛其坤", keywords: ["李德仁", "薛其坤"] },
  { id: "f66", type: "fill", section: "scientist", source: "公开资料整理",
    question: "我国首位获得诺贝尔科学奖项的女科学家是____，她于____年获诺贝尔生理学或医学奖，成果是发现____。",
    answer: "屠呦呦；2015；青蒿素", keywords: ["屠呦呦", "2015", "青蒿素"] },
  { id: "f67", type: "fill", section: "scientist", source: "公开资料整理",
    question: "2019年获“共和国勋章”的科学家有五位：于敏、孙家栋、____、____、____。",
    answer: "袁隆平、黄旭华、屠呦呦", keywords: ["袁隆平", "黄旭华", "屠呦呦"] },
  { id: "f68", type: "fill", section: "scientist", source: "公开资料整理",
    question: "2020年因抗击新冠肺炎疫情被授予“共和国勋章”的是____。",
    answer: "钟南山", keywords: ["钟南山"] },
  { id: "f69", type: "fill", section: "scientist", source: "公开资料整理",
    question: "2024年国庆75周年之际获“共和国勋章”的科学家是____、____、李振声；同年获“人民科学家”国家荣誉称号的是____和赵忠贤。",
    answer: "王永志、王振义；王小谟", keywords: ["王永志", "王振义", "王小谟"] },
  { id: "f70", type: "fill", section: "scientist", source: "公开资料整理",
    question: "载人航天精神的16字内容是：特别能吃苦、特别能____、特别能攻关、特别能____。",
    answer: "战斗；奉献", keywords: ["战斗", "奉献"] },
  { id: "f71", type: "fill", section: "scientist", source: "公开资料整理",
    question: "黄大年回国第____年，中国首台万米大陆科学钻探工程样机“____”问世，中国成为世界第____个掌握万米钻探技术的国家。",
    answer: "三；地壳一号；三", keywords: ["三", "地壳一号"] },
  { id: "f72", type: "fill", section: "scientist", source: "公开资料整理",
    question: "1986年3月提出《关于跟踪研究外国战略性高技术发展的建议》、催生“863”计划的四位科学家是____、____、杨嘉墀、____。",
    answer: "王大珩、王淦昌、陈芳允", keywords: ["王大珩", "王淦昌", "陈芳允"] },
  { id: "f73", type: "fill", section: "scientist", source: "公开资料整理",
    question: "每年____月____日是全国科技工作者日（2016年设立）。",
    answer: "5月30日", keywords: ["5", "30"] },

  { id: "c01", type: "flash", section: "scientist", source: "高频简答",
    question: "写出“两弹一星”精神的完整内涵（24字）。",
    answer: "热爱祖国、无私奉献，自力更生、艰苦奋斗，大力协同、勇于登攀。" },
  { id: "c02", type: "flash", section: "scientist", source: "高频简答",
    question: "“两弹一星”精神对当时国家发展的影响？",
    answer: "①不仅促进了国防事业的发展，而且带动了科技事业的发展；②培养了一批吃苦耐劳、勇于创新的科技队伍；③极大地增强了中国人民的信心，推动了社会主义事业的发展。它是爱国主义、集体主义、社会主义精神和科学精神的活生生体现，是中国人民在20世纪为中华民族创造的新的宝贵精神财富。" },
  { id: "c03", type: "flash", section: "scientist", source: "高频简答",
    question: "写出“科学家精神”的六个方面。",
    answer: "胸怀祖国、服务人民的爱国精神；勇攀高峰、敢为人先的创新精神；追求真理、严谨治学的求实精神；淡泊名利、潜心研究的奉献精神；集智攻关、团结协作的协同精神；甘为人梯、奖掖后学的育人精神。" },
  { id: "c04", type: "flash", section: "scientist", source: "高频简答",
    question: "写出伟大抗疫精神的20字内容。",
    answer: "生命至上，举国同心，舍生忘死，尊重科学，命运与共。（2020年9月8日全国抗击新冠肺炎疫情表彰大会提出；钟南山获“共和国勋章”，张伯礼、张定宇、陈薇获“人民英雄”称号）" },
  { id: "c05", type: "flash", section: "scientist", source: "必背名单",
    question: "完整写出23位“两弹一星”功勋奖章获得者名单。",
    answer: "钱三强、钱骥、姚桐斌、赵九章、邓稼先、王淦昌、彭桓武、程开甲、黄纬禄、屠守锷、钱学森、周光召、杨嘉墀、陈能宽、陈芳允、吴自良、任新民、孙家栋、朱光亚、王希季、王大珩、于敏、郭永怀。" },
  { id: "c06", type: "flash", section: "scientist", source: "高频简答",
    question: "从伟大科学家身上你学到了什么？（谈弘扬科学家精神的意义）",
    answer: "答题框架：①爱国——科学没有国界，但科学家有祖国（钱三强、钱学森毅然回国）；②奉献——隐姓埋名、淡泊名利（邓稼先28年、黄旭华30年、程开甲20年）；③协同——大力协同、集智攻关（两弹一星举国体制）；④育人——甘为人梯、奖掖后学（一代代科学家培养青年人才）。结合自身：把个人理想融入国家需要，在学习科研中践行科学家精神。" },
  { id: "c07", type: "flash", section: "scientist", source: "元勋问答",
    question: "吴自良：哪方面专家？制造原子弹时期牵头攻克了哪个核心部件？",
    answer: "材料科学（冶金科学）专家；牵头攻克“甲种分离膜”。主要贡献：低合金钢研究、应变时效研究、分离膜研制、氧扩散机制研究。" },
  { id: "c08", type: "flash", section: "scientist", source: "元勋问答",
    question: "任新民：哪方面专家？担任了哪六项大型航天工程的总设计师？",
    answer: "航天技术与液体火箭发动机技术专家；担任试验卫星通信、实用卫星通信、风云一号气象卫星、发射外国卫星等六项大型航天工程总设计师。" },
  { id: "c09", type: "flash", section: "scientist", source: "元勋问答",
    question: "孙家栋：他的两个“总设计师”身份是什么？",
    answer: "中国第一颗人造地球卫星（东方红一号）总设计师；中国探月工程总设计师。他见证了中国卫星第一次和第一百次发射。" },
  { id: "c10", type: "flash", section: "scientist", source: "元勋问答",
    question: "钱三强：在法国研究哪一项目取得突破？是中国什么事业的创始人？",
    answer: "铀核三裂变研究取得突破性成果；中国原子能科学事业的创始人，被誉为“中国原子弹之父”“中国原子能科学之父”。" },
  { id: "c11", type: "flash", section: "scientist", source: "元勋问答",
    question: "钱骥：他是中国第一颗卫星什么方案的总体负责人？1964年发表什么获国家科委科学二等奖？",
    answer: "“东方红一号”方案总体负责人；1964年发表《气象火箭测高空风的方法》。" },
  { id: "c12", type: "flash", section: "scientist", source: "元勋问答",
    question: "姚桐斌：在哪入党？为哪方面发展做出重要贡献？",
    answer: "1956年9月在中国驻瑞士使馆加入中国共产党（唯一在国外入党的元勋）；为航天材料与工艺技术的发展做出重要贡献，1985年获国家科学技术进步特等奖。" },
  { id: "c13", type: "flash", section: "scientist", source: "元勋问答",
    question: "赵九章：1958年10月提出了什么重要建议？他的称号是什么？",
    answer: "提出“中国发展人造卫星要走自力更生的道路，要由小到大、由低级到高级”的重要建议；被誉为“中国人造卫星之父”。" },
  { id: "c14", type: "flash", section: "scientist", source: "元勋问答",
    question: "邓稼先：如何引领中国独立研究设计核武器的第一步？如何评价他与周光召合写的著作？",
    answer: "1958年起组织领导爆轰物理、流体力学、状态方程、中子输运等基础理论研究，对原子弹物理过程进行大量模拟计算。《我国第一颗原子弹理论研究总结》是核武器理论设计开创性的基础巨著，是培养科研人员的入门教科书。" },
  { id: "c15", type: "flash", section: "scientist", source: "元勋问答",
    question: "朱光亚：哪一年当选院士？与中国第一个核电站的关系？",
    answer: "1994年当选首批中国工程院院士；参加了中国大陆第一个核电站——秦山核电站的相关工作。他被誉为“中国工程科学界支柱性的科学家”“中国科技众帅之帅”。" },
  { id: "c16", type: "flash", section: "scientist", source: "元勋问答",
    question: "王希季：提出“空间资源”概念的是谁？他提出了中国第一个运载火箭什么型号的技术方案？",
    answer: "王希季提出“空间资源”概念；提出长征一号技术方案并负责完成方案阶段研制，1960年2月主持发射中国第一枚液体燃料探空火箭。" },
  { id: "c17", type: "flash", section: "scientist", source: "元勋问答",
    question: "王大珩：称号和代表性“第一”有哪些？",
    answer: "“中国光学之父”；组织研制中国第一片光学玻璃、第一台电子显微镜、第一台激光器和第一个遥感科学规划；863计划四位倡议者之一。" },
  { id: "c18", type: "flash", section: "scientist", source: "元勋问答",
    question: "程开甲：在核武器研制试验中的突出贡献是什么？主要贡献领域有哪些？",
    answer: "隐姓埋名20年（“核司令”），开创、规划并领导了抗辐射加固技术新领域研究；主要贡献：内耗理论、双带理论、核试验、抗辐射加固、超硬材料；也是中国定向能高功率微波研究新领域的开创者之一。" },
  { id: "c19", type: "flash", section: "scientist", source: "元勋问答",
    question: "黄纬禄：被誉为什么？“一弹两用”指什么？",
    answer: "“巨浪之父”“东风-21之父”“航天老总”；提出“一弹两用”设想，将潜地导弹搬上岸，研制成功陆基机动固体战略导弹武器系统，开拓了中国固体火箭与导弹发展的正确道路。1999年获“两弹一星”功勋奖章。" },
  { id: "c20", type: "flash", section: "scientist", source: "元勋问答",
    question: "屠守锷：主要个人成就有哪些？",
    answer: "近程导弹东风二号和中程导弹东风三号设计师，洲际战略导弹东风五号总设计师，长征二号运载火箭总设计师，长征二号捆绑式运载火箭技术总顾问；“中国航天四老”之一，1999年获“两弹一星”功勋奖章。" },
  { id: "c21", type: "flash", section: "scientist", source: "元勋问答",
    question: "王淦昌：什么设想使中国走在世界前列？1986年3月他与谁联合提出了什么建议？",
    answer: "提出用激光打靶实现核聚变（激光惯性约束核聚变）的设想；1986年3月与王大珩、陈芳允、杨嘉墀联合提出《关于跟踪研究外国战略性高技术发展的建议》，催生了“863”计划。" },
  { id: "c22", type: "flash", section: "scientist", source: "元勋问答",
    question: "于敏：一生有哪些主要成就？",
    answer: "在氢弹原理突破中解决了热核武器物理一系列基础问题，提出从原理到构形基本完整的设想（“于敏构型”），起了关键作用；长期领导核武器理论研究设计；从20世纪70年代起在倡导推动若干高科技项目研究中发挥重要作用；把原子核理论分为实验现象和规律、唯象理论、理论基础三个层次。" },
  { id: "c23", type: "flash", section: "scientist", source: "元勋问答",
    question: "郭永怀：主要学术贡献是什么？有何特殊身份？",
    answer: "发现上临界马赫数，发展奇异摄动理论中的变形坐标法（国际公认的PLK方法），倡导高超声速流、电磁流体力学、爆炸力学研究；1999年被追授“两弹一星”功勋奖章，是23位元勋中唯一一位获得“烈士”称号的科学家。" },
  { id: "c24", type: "flash", section: "scientist", source: "元勋问答",
    question: "南仁东：主要事迹和贡献？",
    answer: "FAST工程首席科学家兼总工程师，“天眼之父”。主持编写FAST立项建议书，确定中性氢、脉冲星、分子谱线、VLBI和地外智慧文明搜寻五大科学目标；20世纪90年代中期舍弃国外高薪回国，从预研到建成历时22年，带领团队走遍贵州上百个洼地选定台址，实现从跟踪模仿到集成创新的跨越。" },
];

// 题库元信息（school 字段只是展示用；实际校情题来自可选的 my-school.js）
window.BANK_META = {
  name: "感恩中国近现代科学家奖助学金 · 笔试题库",
  school: "通用版",
  rule: "笔试满分100分（折算20分计入总分），闭卷60分钟；题型：单选、多选、填空、简答",
  sources: ["第六届真题", "2022回忆卷", "2023回忆卷", "博雅书院真题", "知识点整理", "元勋问答", "国家最高科学技术奖/共和国勋章/航天里程碑（公开资料）"]
};
